### ISSUE TITLE
Add www-client/torbrowser to the Gentoo tree

### ISSUE THREAD

**Issue by monsieurp** [MeisterP/torbrowser-overlay#21]
Hi

Title says it all. :) Would be okay with that? Let me know!

**Comment by MeisterP** [comment]
Upstream only supports building torbrowser with their reproducible build
system and not directly from the git repo like I do in the ebuild.
Therefore, I wouldn't move it to the main tree since this evokes the
impression, that it is a fully supported package.

hasufell and I actually removed it from the tree after the discussion in https://bugs.gentoo.org/show_bug.cgi?id=434652
The Tor upstream supported way is to install the torbrowser bundle with "www-client/torbrowser-launcher". Everything else is experimental and doesn't guarantee users privacy and security.

**Comment by monsieurp** [comment]
Oh, ok. Fair enoug. I didn't know about this bug. Thanks.
