### ISSUE TITLE
torbrowser-launcher should depend on dev-python/distro

### ISSUE THREAD

**Issue by corvus1** [MeisterP/torbrowser-overlay#48]
New dep is introduced here: https://github.com/micahflee/torbrowser-launcher/pull/484

Without it, torbrowser launcher fails to emerge with:

`>>> Compiling source in /var/tmp/portage/www-client/torbrowser-launcher-0.3.3/work/torbrowser-launcher-0.3.3 ...
python3.8 setup.py build -j 16
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'`

In addition, I'm not quite sure why we needed to add `distro` by patching it in. I think ebuilds will only run on a very few distributions.

**Comment by MeisterP** [comment]
> In addition, I'm not quite sure why we needed to add `distro` by patching it in. I think ebuilds will only run on a very few distributions.

Because for the patch you've linked to in https://github.com/MeisterP/torbrowser-overlay/issues/45 there is no upstream pull request. For the one that requires `dev-python/distro` there is one at https://github.com/micahflee/torbrowser-launcher/pull/484

I generally prefer to stick to patches proposed for inclusion upstream.

**Comment by corvus1** [comment]
Well, that's fair enough, however, the ebuild still needs to pull dev-python/distro in this case.

**Comment by MeisterP** [comment]
Will keep an eye on https://github.com/micahflee/torbrowser-launcher/pull/484 and https://github.com/micahflee/torbrowser-launcher/issues/446 to see what upstream comes up with and adjust accordingly.

Thanks for the report :)
