### ISSUE TITLE
Why not to add to the main Portage tree?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [MeisterP/torbrowser-overlay#52]
In main Portage tree it will be easier to install and it will get better support from Gentoo community.

**Comment by MeisterP** [comment]
Upstream only supports building torbrowser with their reproducible build system and not directly from the git repo like I do in the ebuild.
Therefore, I wouldn't move it to the main tree since this evokes the impression, that it is a fully supported package.

hasufell and I actually removed it from the tree after the discussion in https://bugs.gentoo.org/434652
The upstream supported way is to install the _torbrowser bundle_ with `www-client/torbrowser-launcher`. Everything else is experimental and doesn't guarantee users privacy and security.

Then there was an effort from a gentoo developer in https://forums.gentoo.org/viewtopic-t-1082722.html not sure why it didn't workout.

**Comment by vitaly-zdanevich** [comment]
But in Gentoo we have 9999 build from git head.
